=== SamOraDur/TPSIT_ChatSocket/projectFiles/src/server/dbChat.dtd
<!ELEMENT Database (UserList,ChatList)>
<!ELEMENT UserList (user*)>
<!ELEMENT ChatList (chat*)>
<!ELEMENT user (password)>
<!ATTLIST user username ID #REQUIRED>
<!ELEMENT password (#PCDATA)>
<!ELEMENT chat (ChatMessage*)>
<!ATTLIST chat id ID #REQUIRED>
<!ELEMENT ChatMessage (Content,Sender,Receiver)>
<!ELEMENT Content (#PCDATA)>
<!ELEMENT Sender (#PCDATA)>
<!ELEMENT Receiver (#PCDATA)>

=== SamOraDur/TPSIT_ChatSocket/projectFiles/src/server/resources/dbChat.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Database SYSTEM "dbChat.dtd">
<Database>
    <UserList>
        <user username="a">
            <password>a</password>
        </user>
        <user username="Bersanella">
            <password>1234</password>
        </user>
        <user username="Ciao">
            <password>Ciao</password>
        </user>
        <user username="dfssdf">
            <password>fsdfds</password>
        </user>
        <user username="Matteo">
            <password>1234</password>
        </user>
        <user username="Test1">
            <password>Test1</password>
        </user>
        <user username="Test2">
            <password>1234</password>
        </user>
        <user username="Test3">
            <password>Ciao</password>
        </user>
        <user username="Test4">
            <password>fsdfds</password>
        </user>
        <user username="Test5">
            <password>1234</password>
        </user>
        <user username="Test6">
            <password>Test1</password>
        </user>
        <user username="Test7">
            <password>1234</password>
        </user>
        <user username="Test8">
            <password>Ciao</password>
        </user>
        <user username="Test9">
            <password>fsdfds</password>
        </user>
        <user username="Test10">
            <password>1234</password>
        </user>
        <user username="Test11">
            <password>Test1</password>
        </user>
    </UserList>
    <ChatList>
        <chat id="SamOraDur-RobMaMingo">
            <ChatMessage>
                <Content>Ciao</Content>
                <Sender>SamOraDur</Sender>
                <Receiver>RobMaMingo</Receiver>
            </ChatMessage>
        </chat>
        <chat id="Bersanella-Ciao">
            <ChatMessage>
                <Content>Ciao</Content>
                <Sender>Ciao</Sender>
                <Receiver>Bersanella</Receiver>
            </ChatMessage>
            <ChatMessage>
                <Content>Ciao2</Content>
                <Sender>Bersanella</Sender>
                <Receiver>Ciao</Receiver>
            </ChatMessage>
        </chat>
    </ChatList>
</Database>
